notARepository: skip
promptToReturnFromSubprocess: false
os:
  edit: "cursor {{filename}}"
  editAtLine: "cursor --line={{line}} {{filename}}"
  editAtLineAndWait: "cursor --block --line={{line}} {{filename}}"
  editInTerminal: true
  openDirInEditor: "cursor {{dir}}"
gui:
  nerdFontsVersion: "3"
  border: rounded
  mouseEvents: false
  screenMode: normal
  theme:
    activeBorderColor:
      - "#5ef1ff"
    inactiveBorderColor:
      - "#7b8496"
    searchingActiveBorderColor:
      - "#ff5ef1"
    optionsTextColor:
      - "#3c4048"
    selectedLineBgColor:
      - "#3c4048"
    cherryPickedCommitBgColor:
      - "#3c4048"
    cherryPickedCommitFgColor:
      - "#ff5ea0"
    unstagedChangesColor:
      - "#ffbd5e"
    defaultFgColor:
      - "#ffffff"
git:
  parseEmoji: true
