#!/usr/bin/env bash
source "$HOME/dotfiles/yabai/yabai_env.sh"

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# general settings
yabai -m config window_shadow on
yabai -m config window_border off
yabai -m config insert_feedback_color 0xff9dd274
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config window_topmost on

# transparency
yabai -m config window_opacity on
yabai -m config active_window_opacity 1
yabai -m config normal_window_opacity 0.98
yabai -m config window_opacity_duration 0.0
yabai -m rule --add app="^${apps_transp_ignore}$" opacity=1

# padding
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

# center mouse on window with focus
yabai -m config mouse_follows_focus off

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier ctrl
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap

function yabai_rule {
  yabai -m rule --add "$@"
  yabai -m rule --apply "$@"
}

# automation rules
# yabai_rule app="^Arc$" space=1 label="assign-arc" sticky=off
yabai_rule app="^Ghostty$" space=2 label="assign-ghostty" sticky=off
yabai_rule app="^Cursor$" space=2 label="assign-cursor" sticky=off
yabai_rule app="^Slack$" space=3 label="assign-slack" sticky=off
yabai_rule app="^Notes$" space=4 label="assign-notes" sticky=off
yabai_rule app="^Reminders$" space=5 label="assign-reminders" sticky=off manage=on
yabai_rule app="^Raindrop.io$" space=6 label="assign-raindrop" sticky=off
yabai_rule app="^Spark$" space=6 label="assign-spark" sticky=off
yabai_rule app="^Discord$" space=7 label="assign-discord" sticky=off
yabai_rule app="^ChatGPT$" space=8 label="assign-chatgpt" sticky=off
yabai_rule app="^Claude$" space=8 label="assign-claude" sticky=off
yabai_rule app="^Trader Workstation$" space=9 label="assign-tws" sticky=off
yabai_rule app="^Spotify$" space=10 label="assign-spotify" sticky=off

# turn off yabai for these apps
yabai_rule app="^System Settings$" manage=off
yabai_rule app="^Calculator$" manage=off
yabai_rule app="^Alfred Preferences$" manage=off
yabai_rule app="^AlDente$" manage=off
yabai_rule app="^Toggl Track$" manage=off
yabai_rule app="^Finder$" manage=off
yabai_rule app="^1Password$" manage=off
yabai_rule app="^Homerow$" manage=off
yabai_rule app="^System Information$" manage=off
yabai_rule app="^Activity Monitor$" manage=off
yabai_rule app="^Trader Workstation$" manage=off
yabai_rule app="^DAS Trader Pro$" manage=off
yabai_rule app="^SierraChart_ARM64.exe$" manage=off

echo "yabai configuration loaded.."
