{
  pkgs,
  config,
  lib,
  ...
}:

let
  commonSystemPackages = import ./system/common-packages.nix { inherit pkgs; };
  username = "blancpain";
  homeDir = "/home/${username}";
in

{
  imports = [
    # Networking configuration
    ./networking.nix
    # Include the results of the hardware scan.
    # This file is generated by nixos-generate-config and should be created on the target system
    # For now, we'll make it optional so the config can be evaluated
    # On actual NixOS install, run: sudo nixos-generate-config --show-hardware-config > ./hardware-configuration.nix
  ]
  ++ (lib.optional (builtins.pathExists ./hardware-configuration.nix) ./hardware-configuration.nix);

  # Boot loader configuration (choose one based on your system)
  boot.loader = {
    # For UEFI systems (most modern computers)
    systemd-boot.enable = lib.mkDefault true;
    efi.canTouchEfiVariables = lib.mkDefault true;

    # Alternative: For GRUB on UEFI
    # grub = {
    #   enable = true;
    #   device = "nodev";
    #   efiSupport = true;
    #   useOSProber = true;
    # };
  };

  # Enable sudo for wheel group
  security.sudo.wheelNeedsPassword = lib.mkDefault true;

  nixpkgs = {
    config.allowUnfree = true;
    hostPlatform = lib.mkDefault "x86_64-linux";
  };

  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

  programs.fish.enable = true;

  environment = {
    systemPackages = commonSystemPackages;
    shells = [ pkgs.fish ];
  };

  users = {
    defaultUserShell = pkgs.fish;
    users.${username} = {
      isNormalUser = true;
      home = homeDir;
      description = username;
      shell = pkgs.fish;
      extraGroups = [ "wheel" ];
    };
  };

  # Set the persisted system version; adjust if you target a different NixOS release.
  system.stateVersion = lib.mkDefault "25.05";
}
