require("user.launch")
require("user.options")
require("user.keymaps")
require("user.autocmds")
spec("user.colorscheme")
spec("user.devicons")
spec("user.treesitter")
spec("user.mason")
spec("user.schemastore")
spec("user.lspconfig")
spec("user.cmp")
spec("user.none-ls")
spec("user.telescope")
spec("user.nvimtree")
spec("user.navic")
spec("user.breadcrumbs")
spec("user.harpoon")
spec("user.whichkey")
spec("user.comment")
spec("user.lualine")
spec("user.extras.copilot")
spec("user.extras.tabby")
spec("user.extras.neoscroll")
spec("user.extras.navbuddy")
spec("user.illuminate")
spec("user.extras.oil")
spec("user.extras.dressing")
spec("user.extras.colorizer")
spec("user.extras.ufo")
spec("user.extras.lab")
spec("user.extras.neotab")
spec("user.extras.bqf") -- GREAT!
spec("user.autopairs")
spec("user.neotest")
spec("user.gitsigns")
spec("user.alpha")
spec("user.project")
spec("user.toggleterm")
spec("user.indentline")
spec("user.neogit") -- prefer lazygit...
-- check out gitLinker
-- add fidget
require("user.lazy")
