return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "html",
      "javascript",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "tsx",
      "typescript",
      "vim",
      "yaml",
      "prisma",
      "sql",
      "css",
      "scss",
      "yaml",
      "vue",
      "nu",
      "nix",
      "latex",
      "typst",
      "rust",
    },
  },
}
